datadog:
  site: "ap1.datadoghq.com"
  apiKeyExistingSecret: "datadog-secret"
  kubelet:
    useApiServer: true
  apm:
    instrumentation:
      enabled: true
      targets:
        - name: "default-target"
          ddTraceVersions:
            java: "1"
            python: "3"
            js: "5"
            php: "1"
            dotnet: "3"
  logs:
    enabled: true
    containerCollectAll: true
agents:
  containers:
    agent:
      resources:
        requests:
          cpu: "200m"
          memory: "256Mi"
    traceAgent:
      resources:
        requests:
          cpu: "100m"
          memory: "200Mi"
    processAgent:
      resources:
        requests:
          cpu: "100m"
          memory: "200Mi"
    systemProbe:
      resources:
        requests:
          cpu: "100m"
          memory: "400Mi"
  priorityClassCreate: true
providers:
  gke:
    autopilot: true
